# Generated by Django 6.0.1 on 2026-03-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rsvp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "spouse_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("number", models.CharField(blank=True, default="", max_length=20)),
                ("response", models.CharField(max_length=20)),
                ("submittedat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
